const STORE='scangoqr.items.v1',DAY=86400000;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let currentType='',currentQR=null,deferredPrompt=null,timerId;
function items(){try{return JSON.parse(localStorage.getItem(STORE))||[]}catch{return[]}}
function put(list){localStorage.setItem(STORE,JSON.stringify(list))}
function clean(){const now=Date.now(),list=items(),valid=list.filter(x=>x.type!=='file'&&(x.keep||now-x.createdAt<DAY));if(valid.length!==list.length)put(valid);return valid}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(timerId);timerId=setTimeout(()=>t.classList.remove('show'),2400)}
function showView(id){if(!document.getElementById(id))id='home';$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));if(id==='saved')renderSaved();scrollTo({top:0,behavior:'smooth'})}
function go(id,replace=false){showView(id);const url=id==='home'?location.pathname+location.search:'#'+id;const method=replace?'replaceState':'pushState';history[method]({view:id},'',url)}
$$('[data-go]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();go(b.dataset.go)}));
$$('[data-type]').forEach(b=>b.addEventListener('click',()=>{currentType=b.dataset.type;$('#typeChooser').hidden=true;$('#qrForm').hidden=false;$('#previewPanel').hidden=true;$('#inputLabel').textContent=currentType==='url'?'Enlace o URL':'Texto';$('#qrValue').placeholder=currentType==='url'?'https://ejemplo.com':'Escribe el texto que contendrá el QR…';$('#qrValue').focus()}));
$('#changeType').onclick=()=>{$('#qrForm').hidden=true;$('#previewPanel').hidden=true;$('#typeChooser').hidden=false;$('#qrValue').value='';currentQR=null};
function normalized(){let value=$('#qrValue').value.trim();if(!value)throw Error('Escribe un contenido para generar el QR.');if(currentType==='url'){if(!/^https?:\/\//i.test(value))value='https://'+value;try{const u=new URL(value);if(!u.hostname.includes('.'))throw 0;return u.href}catch{throw Error('Escribe una URL válida, por ejemplo: https://ejemplo.com')}}return value}
async function makeData(value){return QRCode.toDataURL(value,{width:900,margin:3,errorCorrectionLevel:'H',color:{dark:'#063c2e',light:'#ffffff'}})}
function showPreview(qr){currentQR=qr;const img=new Image;img.onload=()=>{const c=$('#previewCanvas');c.width=900;c.height=900;c.getContext('2d').drawImage(img,0,0)};img.src=qr.data;$('#previewType').textContent=qr.type==='url'?'ENLACE':'TEXTO';$('#previewText').textContent=qr.value;$('#pdfHint').textContent=qr.type==='url'?'En el PDF también podrás tocar o hacer clic sobre el QR para abrir el enlace.':'';$('#previewPanel').hidden=false;$('#previewPanel').scrollIntoView({behavior:'smooth'})}
$('#qrForm').addEventListener('submit',async e=>{e.preventDefault();try{const value=normalized(),data=await makeData(value);showPreview({id:crypto.randomUUID?crypto.randomUUID():Date.now().toString(36),type:currentType,value,data,createdAt:Date.now(),keep:false});$('#formError').textContent=''}catch(err){$('#formError').textContent=err.message}});
$('#saveQR').onclick=()=>{if(!currentQR)return;const list=clean();if(!list.some(x=>x.id===currentQR.id)){list.unshift(currentQR);try{put(list);toast('QR guardado durante 24 horas')}catch{toast('No hay espacio disponible para guardar más QR')}}else toast('Este QR ya está guardado')};
function filename(x,ext){return `ScanGoQR_${x.type}_${new Date(x.createdAt).toISOString().slice(0,10)}.${ext}`}
function download(blob,name){const a=document.createElement('a');a.href=typeof blob==='string'?blob:URL.createObjectURL(blob);a.download=name;a.click();if(typeof blob!=='string')setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function jpeg(x){const img=new Image;img.onload=()=>{const c=document.createElement('canvas');c.width=c.height=1200;const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,1200,1200);g.drawImage(img,100,100,1000,1000);download(c.toDataURL('image/jpeg',.96),filename(x,'jpg'))};img.src=x.data}
function pdf(x){const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'mm',format:'a4'});doc.setTextColor(6,60,46);doc.setFontSize(22);doc.text('ScanGoQR',105,24,{align:'center'});doc.addImage(x.data,'PNG',45,42,120,120);if(x.type==='url'){doc.link(45,42,120,120,{url:x.value});doc.setFontSize(10);doc.setTextColor(70);doc.text('Toca o haz clic en el código QR para abrir el enlace.',105,172,{align:'center'});doc.setTextColor(7,85,61);doc.textWithLink(x.value.slice(0,85),105,180,{url:x.value,align:'center'})}else{doc.setFontSize(10);doc.setTextColor(70);doc.text(doc.splitTextToSize(x.value,170).slice(0,8),20,175)}doc.save(filename(x,'pdf'))}
$('#downloadJpg').onclick=()=>currentQR&&jpeg(currentQR);$('#downloadPdf').onclick=()=>currentQR&&pdf(currentQR);
function remaining(x){const ms=Math.max(0,DAY-(Date.now()-x.createdAt)),h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return `${h} h ${m} min restantes`}
function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function setKeep(q,keep){const a=items(),item=a.find(v=>v.id===q.id);item.keep=keep;if(!keep)item.createdAt=Date.now();put(a)}
function removeQR(q){put(items().filter(x=>x.id!==q.id))}
const qrViewer=$('#qrViewer');
function openQrViewer(q){$('#qrViewerImg').src=q.data;$('#qrViewerTitle').textContent=q.type==='url'?'QR de enlace':'QR de texto';$('#qrViewerText').textContent=q.value;qrViewer.showModal();history.pushState({view:'saved',qrModal:true},'','#saved-qr')}
function closeQrViewer(fromHistory=false){if(qrViewer.open)qrViewer.close();if(!fromHistory&&history.state?.qrModal)history.back()}
$('#closeQrViewer').onclick=()=>closeQrViewer();qrViewer.addEventListener('click',e=>{if(e.target===qrViewer)closeQrViewer()});
function renderSaved(){const list=clean(),box=$('#savedList');box.innerHTML='';$('#emptyState').hidden=!!list.length;list.forEach(x=>{const el=document.createElement('article');el.className='saved-card';const label=x.type==='url'?'Enlace web':'Texto';el.innerHTML=`<button class="qr-thumb" data-viewqr="${x.id}" aria-label="Ver código QR completo"><img src="${x.data}" alt="Código QR"></button><div><h3>${label}</h3><p class="saved-value">${esc(x.value)}</p><span class="timer">${x.keep?'Conservado permanentemente':remaining(x)}</span><label class="keep"><input type="checkbox" data-keep="${x.id}" ${x.keep?'checked':''}> Conservar (no borrar)</label><div class="card-actions"><button class="secondary" data-jpg="${x.id}">JPEG</button><button class="secondary" data-pdf="${x.id}">PDF</button><button class="danger" data-delete="${x.id}">Eliminar</button></div></div>`;box.append(el)});box.querySelectorAll('[data-viewqr]').forEach(b=>b.onclick=()=>openQrViewer(items().find(x=>x.id===b.dataset.viewqr)));box.querySelectorAll('[data-keep]').forEach(c=>c.onchange=()=>{const q=items().find(v=>v.id===c.dataset.keep);setKeep(q,c.checked);renderSaved();toast(c.checked?'QR protegido':'Nuevo periodo de 24 horas iniciado')});box.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('¿Eliminar este código QR?')){removeQR(items().find(x=>x.id===b.dataset.delete));renderSaved();toast('QR eliminado')}});box.querySelectorAll('[data-jpg]').forEach(b=>b.onclick=()=>jpeg(items().find(x=>x.id===b.dataset.jpg)));box.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>pdf(items().find(x=>x.id===b.dataset.pdf)))}
setInterval(()=>{if($('#saved').classList.contains('active'))renderSaved()},60000);clean();window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}else toast('Usa el menú del navegador y elige “Instalar aplicación”')};window.addEventListener('appinstalled',()=>toast('ScanGoQR instalada'));if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));const initialRoute=['create','saved'].includes(location.hash.slice(1))?location.hash.slice(1):'home';showView(initialRoute);history.replaceState({view:initialRoute},'',initialRoute==='home'?location.pathname+location.search:'#'+initialRoute);window.addEventListener('popstate',e=>{if(qrViewer.open)closeQrViewer(true);showView(e.state?.view||'home')});
