name = "scangoqr-cloud"
main = "src/worker.mjs"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGIN = "https://TU-USUARIO.github.io"

[[r2_buckets]]
binding = "FILES"
bucket_name = "scangoqr-files"

[[d1_databases]]
binding = "DB"
database_name = "scangoqr-db"
database_id = "PEGA_AQUI_EL_ID_DE_D1"

[triggers]
crons = ["0 * * * *"]
